### ISSUE TITLE
Only works while having sex with Francine!

### ISSUE THREAD

**Issue by namzop** [CodeWithSwastik/swas#9]
Hey Swas, I've found a bug in the code! Your language swas only works while having sex with your gf Francine, it doesn't work if you're not having sex. Please fix this bug or just give me Francine so that I can use your language!

**Comment by AHiddenDonut** [comment]
bruv xdddd

**Comment by PlebusSupremus** [comment]
yes i was experiencing that bug too. really disgusting language, i mean who would want to sex with francine
